name: megaoverflowradio
description: Mega Overflow Radio
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.46
  just_audio_background: ^0.0.1-beta.13
  audio_session: ^0.1.21
  http: ^1.1.0
  google_mobile_ads: ^5.3.1
  url_launcher: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/icon/logo.png
