name: megaoverflowradio
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.40
  just_audio_background: ^0.0.1-beta.14
  audio_session: ^0.1.21
  audio_service: ^0.18.12
  http: ^1.1.2
  url_launcher: ^6.2.0
  google_mobile_ads: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/icon/logo.png